jonls/redshift

- src/redshift.c
No need to bother valgrind -- though I would love to know if it would have spotted the problem. I dug a bit deeper and found the culprit. At first I was wondering why the compiler was not complaining. But now I know:
```
typedef int gamma_method_set_temperature_func(void *state,
const color_setting_t *setting);
```
It does not know what to expect.
fixes #157
> fixes #157: it was a tiny oversight during refactoring

- src/redshift.c
Fixes #188
79aafd07fc49e09708d7475d7b3ccb19ede061b7 is a rewrite of christian-burger/redshift@c611b95ea0c47b459900929ba7828db2e006cec7
----
**Commit Messages:**
83bf2a37ad617372b9c5dc8ab83cf535afb66321
Fix CLAMP macro by renaming it to BETWEEN
Fixes #188
When I moved the macro definition below all of the includes, I got the
following compiler warning:
/usr/include/glib-2.0/glib/gmacros.h:246:0: note: this is the location
of the previous definition
#define CLAMP(x, low, high)  (((x) > (high)) ? (high) : (((x) < (low))
? (low) : (x)))
So, that's the macro definition that was being used whenever "CLAMP" was
used. It's pretty obvious why that's wrong.
79aafd07fc49e09708d7475d7b3ccb19ede061b7
Fix temperature getting out of bounds
bug was introduced by refactoring at …
> Fix clamp issues

- src/redshift-gtk/statusicon.py
This fixes a warning when starting redshift-gtk with gtk 3.18.
> Specify required Gtk version

- redshift.1
My colleague and I installed redshift hooks on our computers and we both read through the manpage. We ended up using different techniques. One of us understood the documentation correct and used a folder with script, the other one create a file called `~/.config/redshift/hooks`.
Of course, after testing, we found the correct way, but the way, how the hooks get called, lets easily assume that there is only a single file (`~/.config/redshift/hooks`), which processes everything. I hope this PR makes this point clear in the documentation.
> Change documentation concerning hooks

- po/fr.po
- redshift.1
The man page had the old night temperature (3700K); the French translation had a `/` in the `-t` usage, instead of `:`.
> Fix a typo in man page and French translation

- data/appdata/redshift-gtk.appdata.xml.in
The current one was 404 not found. See https://software.opensuse.org/package/redshift-gtk which makes use of the link provided in the URL.
> Fixed the screenshot URL.

- src/gamma-drm.c
See #343. Variable length arrays are supported in C99 and can be used in place of alloca().
> drm: Avoid using alloca()

- HACKING.md
There was a typo in `i686-w64-mingw32` (missing "n").
> Fixed typo in HACKING.md in the host parameter for cross compiling 32-bit builds

- contrib/macos/launchd/dk.jonls.redshift.plist
Add launchd file for macOS in `contrib` directory as suggested in #398.
> contrib: Add launchd file for macOS

- src/gamma-randr.c
- src/gamma-randr.h
> XRandR: Allow multiple but not all CRTCs to be redshifted

- src/redshift.c
As suggested in #262, a default value of 6500K for the daytime temperature would probably work better for most users. 4500K was suggested as the default nighttime temperature since it is less extreme. As always, the configuration file or command line can be used to select different temperatures.
> redshift.c: Use 6500K and 4500K by default

- appveyor.yml
This ensures that all files required for Windows build are correctly bundled in the source archive produced by autotools.
In the zip package, various text files are renamed with .txt extension to make it easier to open these files on Windows. Also bundles the sample configuration file.
> Appveyor: Run distcheck and improve zip package

- src/redshift-gtk/Makefile.am
- src/redshift-gtk/controller.py
- src/redshift-gtk/statusicon.py
- src/redshift-gtk/utils.py
Moves controller to separate file and applies various fixes:
- Fixes for #220 provided by @agnivade.
- Makes the `xdg` module optional (`Autostart` checkbox is hidden if not available)
- Uses GtkWindow instead of GtkDialog to avoid warnings when a GtkDialog is used without a parent window.
- PEP8
> Updates to redshift-gtk

- src/redshift-gtk/utils.py
Although not named like modules, the BaseDirectory and
DesktopEntry are really submodules of xdg that need to be imported
for them to be available.
> Fix #492: Correctly import xdg modules

- .travis.yml
- appveyor.yml
- configure.ac
- src/Makefile.am
- src/location-corelocation.h
- src/location-corelocation.m
- src/location-geoclue2.c
- src/location-geoclue2.h
- src/location-manual.c
- src/location-manual.h
- src/pipeutils.c
- src/pipeutils.h
- src/redshift.c
- src/redshift.h
- Fixes #13 (also fixes #387).
- For #36/#251/#348/#393/#396, we still don't cache the location on disk but if the location provider becomes unavailable, the last returned location is used until the location provider is able to provide updates again. In other  words, at the moment we cache the last location in the running instance of redshift but not if redshift is restarted.
- This probably also fixes issues such as #150, #176, #226, #318, #333 (though it doesn't fix the issues where Redshift cannot connect to GeoClue2 because the location services are not enabled/not allowed for Redshift).
> Continuous location updates

- README.md
- src/location-geoclue2.c
This adds a better explanation when access to the location from GeoClue is denied. This is similar to #480 and is based on the discussion in #289.
> GeoClue: better error message when access is denied

- src/gamma-quartz.c
- src/gamma-randr.c
- src/gamma-vidmode.c
- src/gamma-w32gdi.c
The gamma ramp adjustment methods (quartz, randr, vidmode and w32gdi) have supported an option to preserve the gamma ramps on startup and apply the redness effect on top of those existing gamma ramps. Previously this option was not enabled by default. Since no issues have been reported so far with this option it is now enabled by default.
> Preserve gamma ramps by default

- .gitignore
- Makefile.am
- configure.ac
- data/apparmor/usr.bin.redshift.in
AppArmor is a Mandatory Access Control mechanism: instead of considering users and groups, like traditional Unix permissions, it considers what process is making the request. More basically, it is a simple way to increase confinement of Redshift by restricting what files redshift can access and other permissions.
With the AppArmor profile in enforcement mode, redshift will not be able to access the users normal files in $HOME -- only its own config file. Furthermore it will be restricted from many other areas of the system that are not necessary to its operation.
> Add AppArmor profile

- .travis.yml
- appveyor.yml
- src/redshift.c
Implements time-based transition periods for dawn and dusk. If time-based adjustments are desired both `dawn-time` and `dusk-time` must be specified in the configuration file:
```
[redshift]
dawn-time=04:00-05:30
dusk-time=18:00
```
These option can specify an interval like `04:00-05:30` or an instant `18:00` which is equivalent to `18:00-18:00`. The transition between day and night color temperature takes place in the specified interval. Currently times must be specified in 24-hour format and the beginning of dawn must be after midnight and the end of dusk must be before midnight.
When time-based adjustment is specified, no location provider is needed and it will therefore not be initialized and used.
> Time-based adjustment

- .travis.yml
AppArmor file was added in #528. Add option to `./configure` in `.travis.yml` so that the AppArmor install is tested.
> Travis: Enable AppArmor install

- src/redshift.c
Rearrange checks and verbose output in main() to bring back checks
that were accidentally left out when time-based adjustments were
enabled. This includes the output indicating the daytime/night
temperatures and the check that the temperatures are valid.
> Fix missing checks and verbose output

- src/gamma-quartz.c
The quartz (macOS) adjustment method incorrectly used the display
index instead of the associated CGDirectDisplayID. Incidentally this
happened to work too but was incorrect.
> quartz: Fix incorrect use of display identifier

- po/POTFILES.in
- src/Makefile.am
- src/gamma-drm.c
- src/gamma-drm.h
- src/gamma-dummy.c
- src/gamma-dummy.h
- src/gamma-quartz.c
- src/gamma-quartz.h
- src/gamma-randr.c
- src/gamma-randr.h
- src/gamma-vidmode.c
- src/gamma-vidmode.h
- src/gamma-w32gdi.c
- src/gamma-w32gdi.h
- src/location-corelocation.h
- src/location-corelocation.m
- src/location-geoclue2.c
- src/location-geoclue2.h
- src/location-manual.c
- src/location-manual.h
- src/options.c
- src/options.h
- src/redshift.c
- src/redshift.h
- Move the struct defining the entry points for each module (adjustment methods and location providers) to their respective files.
- Make each module allocate its own state data so the structs can be opaque and `redshift.c` doesn't need to know about them.
- Move the state structs out of the header files and into the `.c` files of their respective modules.
- Move options parsing to new `options.c`.
- Add function to simplify resetting `color_setting_t`.
> Cleanup redshift.c + modules + options

- redshift.1
- src/gamma-drm.c
- src/gamma-dummy.c
- src/gamma-quartz.c
- src/gamma-randr.c
- src/gamma-vidmode.c
- src/gamma-w32gdi.c
- src/options.c
- src/options.h
- src/redshift.c
- src/redshift.h
Changes each adjustment method to take a preserve parameter when
setting the temperature instead of parsing the preserve option
from the command line/configuration file. This helps resolve the
issues around #513:
- This allows the preserve option to be implemented as a
command-line switch (-P). This switch _disables_ the preservation
of existing gamma ramps. Having a command-line switch makes it
easier to use directly with manual or one-shot mode.
- The preserve options is on by default, so continual mode as well
as other modes will default to applying the color adjustment
on top of the current gamma ramps.
- Preserve is always disabled in reset mode so resetting works
as expected again.
> Preserve command-line option

- src/redshift.c
This allows for hooks to be run when redshift is disabled. See #335
> Fix #335: Set period to none when disabled

- .travis.yml
As of March 2018, Travis CI fails on macOS:
```
Error: python 2.7.14 is already installed
To upgrade to 3.6.4_4, run `brew upgrade python`
```
This commit fixes the issue.
> Travis: Run "brew upgrade python" to install Python 3 on macOS

- .travis.yml
Fix #643.
* Temporary workaround for `distuninstallcheck` error.
* Get upstream patch (https://git.savannah.gnu.org/cgit/automake.git/patch/?id=a348d830659fffd2cfc42994524783b07e69b4b5) and apply it before running `./bootstrap`.
> Travis: Fix automake on macOS

- contrib/redshift.spec
Hi Jon,
Just tried building the rpm packages for my own system as fedora 28 has not yet provided a 1.12 package. While doing so I noticed the spec file was not updated from 1.11 to 1.12. The attached commit fixes this issue.
Kind regards,
Ben
> Update rpm spec file to version 1.12

- src/config-ini.c
- src/gamma-drm.c
- src/gamma-dummy.c
- src/gamma-randr.c
- src/gamma-vidmode.c
- src/gamma-w32gdi.c
- src/location-geoclue2.c
- src/location-manual.c
`ENABLE_NLS` is always undefined in some files and some translatable messages in these files are always displayed in English. This commit fixes the issue.
Files:
* `config-ini.c`
* `gamma-drm.c`
* `gamma-dummy.c`
* `gamma-randr.c`
* `gamma-vidmode.c`
* `gamma-w32gdi.c`
* `location-geoclue2.c`
* `location-manual.c`
Examples:
* `redshift -m randr:help`
* `redshift -l manual:help`
> Fix "Some translated strings are still in English" issue

- src/redshift.c
AppVeyor's GCC no longer supports `localtime_r()`:
```
make[4]: Entering directory '/c/projects/redshift/redshift-1.12/_build/sub/src'
CC       colorramp.o
CC       config-ini.o
CC       gamma-dummy.o
CC       hooks.o
CC       location-manual.o
CC       options.o
CC       pipeutils.o
CC       redshift.o
../../../src/redshift.c: In function 'get_seconds_since_midnight':
../../../src/redshift.c:213:2: warning: implicit declaration of function 'localtime_r'; did you mean 'localtime_s'? [-Wimplicit-function-declaration]
213 |  localtime_r(&t, &tm);
|  ^~~~~~~~~~~
|  localtime_s
CC       signals.o
CC       solar.o
CC       systemtime.o
CC       gamma-w32gdi.o
GEN      windows/appicon.o
GEN      windows/versioninfo.o
OBJCLD   redshift.exe
redshift.o: In function `get_seconds_since_midnight': …
```
> src/redshift.c: Use localtime_s() on Windows
