jonls/redshift

.gitignore
Makefile.am
contrib/redshift.spec
data/applications/redshift.desktop.in
po/POTFILES.in

This should fix the fact that redshift cannot query its location using
geoclue 2

Add a redshift desktop file (#158)

---

redshift.1

Apply manual page adjustments suggested by rjc in #266.

Fix #266: manual page adjustments

---

po/ru.po

Updated russian translation

---

po/nl.po

Update for the Dutch translation. Some untranslated sentences or words
are now translated into Dutch. Note that not all sentences are translated yet.

Translations: Update Dutch translation

---

src/redshift-gtk/statusicon.py

Instead of calling sys.exit() the signal handlers now try to terminate the child process. After the child exits, the process will be reaped by the GLib callback which will call Gtk.main_quit() which will then quit redshift-gtk. This ensures that the redshift process does not outlive the redshift-gtk process.

 redshift-gtk: Make sure that child process is closed after signals (WIP)

---

po/LINGUAS
po/sr.po

Created the initial translation to the Serbian language. Because my interest lies in the redshift-gtk client, I have translated all the strings it uses (although some translated strings do not appear in the gui).

Added initial Serbian translation.

---

po/pt_BR.po

Update l10n strings on pt_BR.po file, using @EvertonMelo effort as base.
Fix #369 MR

Update pt_BR.po file

---

src/redshift-gtk/statusicon.py

add display of color temperature and period in the tooltip status icon

---

README.md

README.md: Add FAQ with known issues

---

redshift.1

see more at #420 and #262 
for the man file (redshift.1)
Thank you very much :)

Change default temperature value

---

README.md
appveyor.yml

Fix #438: Add AppVeyor configuration

---

appveyor.yml

Try to build static executable and disable NLS

---

src/redshift.c

I think I would also need to make changes to the `redshift.1` file [here](https://github.com/jonls/redshift/blob/master/redshift.1#L75-L79) and the translation files, though I'm not sure.

Formatted help text paragraph to 80 chars max

---

redshift.1
redshift.conf.sample
src/redshift.c

This should clear up some of the confusion about the short fades.

Use the term "fade" instead of "transition" for the short (~5s) fade between color temperatures

---

src/redshift.c

Simplify implementation of fades in continual mode. A fade is now
applied anytime the change in color temperature, brightness or
gamma is greater than a preset threshold. This means that a fade
is applied if the location provider suddenly updates to a new
location or if the currently time suddenly jumps e.g. after waking
up the computer from sleep. An easing function is applied to the
fade to make it more pleasant.

redshift: Improve fade implementation

---

src/gamma-w32gdi.c

We have to retry SetDeviceGammaRamp a few times before giving up
because some buggy drivers fail on the first invocation just to
succeed on the second.

Fix #523: Retry SetDeviceGammaRamp before giving up

---

redshift.1
redshift.conf.sample

Add documentation for `dawn-time` and `dusk-time` options in man page and sample configuration file.

Add documentation for time-based adjustment

---

src/redshift-gtk/statusicon.py

Add help message to redshift-gtk

---

redshift.1

- Improve man page based on guidelines in https://liw.fi/manpages/.
- Fix #448 by mentioning `redshift-gtk` in the man page.

Improve man page

---

README.md
data/apparmor/usr.bin.redshift.in
redshift.1

Because of commit 9ff0501.
Related #608.

README, man, apparmor: Update configuration file path

---

.editorconfig
.gitignore

- Clean up `.gitignore`
- Add `.editorconfig`

Update dot files

---

src/redshift-gtk/statusicon.py

Use 'redshift-status-on-symbolic' and 'redshift-status-off-symbolic'
if available.
If these icons are not present in the icon theme, fallback to
'redshift-status-on' and 'redshift-status-off'.
Symbolic icons are the only way for themes to properly support
both light and dark panels with grey icons. If the icon name ends
with -symbolic, GTK renders the foreground color of the icon based
on the color of the panel behind it.
The screenshot above illustrates the problem and the solution. The icon theme is using monochrome fullcolor icons. The panel on top uses a GTK theme which has a dark panel. The panel below uses a GTK theme wich has a light panel.
nm-applet, mate-volume-control and onboard use these icons. Although they look nice in the dark panel, the icon theme is completely broken with …

Status icon: Prefer symbolic icons when available

---

CONTRIBUTING.md
README.md

Fixes to documentation on contributing

---

src/redshift-gtk/statusicon.py

Hello,
- From the open issue > https://github.com/jonls/redshift/issues/386 ~ I added the two suspend options, built the project with the new changes and tested each option to ensure that they are working.
- Let me know what you think.
hubvu

Fix #386: added more suspend durations as requested
